name = "Blade"
grammar = "blade"
path_suffixes = ["blade.php"]
block_comment = ["{{-- ", " --}}"]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = false, newline = true },
    { start = "{{", end = "}}", close = false, newline = false },
    { start = "{!!", end = "!!}", close = false, newline = false },
    { start = "{{--", end = "--}}", close = false, newline = false },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string"] },
]
word_characters = ["-"]
scope_opt_in_language_servers = ["tailwindcss-language-server"]
prettier_plugins = ["@shufo/prettier-plugin-blade"]
prettier_parser_name = "blade"

[overrides.element]
word_characters = ["-"]

[overrides.string]
word_characters = ["-"]
opt_into_language_servers = ["tailwindcss-language-server"]
